### ISSUE TITLE
Segment alignment feature

### ISSUE THREAD

**Issue by hilalbaig** [tahseen0amin/TZSegmentedControl#2]
Hello,

I'm adding a new property 'segmentAlignment'.

Its default value will be `edge` that keeps default behaviour of UIScrollView of aligning subviews to the edges.

Value `center` will change behaviour, so all subviews, including first and last ones, would be centered in the underlying UIScrollView.

**Comment by hilalbaig** [comment]
Done in #3

**Comment by tahseen0amin** [comment]
Hilal,

Thanks for adding this feature. 

I have accepted your pull request and was testing the feature. It works as expected and mentioned above, but here is what I think will take it to next level. If you add this, it will be highly appreciated.

If value 'center' us selected.

- [ ] Tapping a selected label, re-center the label in the underlying UIScrollView.

- [ ] Once a user has stopped scrolling, check if the selected label is centered. If not, animate and re-center it.

Let me know if you have any question.
Again, thanks for your efforts.

Cheers
Tasin

**Comment by hilalbaig** [comment]
First part is done in, will try my best to take out time for second one. 
- [x] Tapping a selected label, re-center the label in the underlying UIScrollView.
- [ ] Once a user has stopped scrolling, check if the selected label is centered. If not, animate and re-center it.

**Comment by hilalbaig** [comment]
The second part look bit ambiguous because i think it will create problems when segment items' width are greater then screen size. As If user wants to scroll to last item that is off the screen, it would be bad if we forcely center selected label in center.

What do you think?

**Comment by tahseen0amin** [comment]
You are right and I was more like thinking about better user experience. If I have to be honest, i wasn’t even knowing of achieving something like that. Since it is your work, I would gladly accept your end result and let others work on top of that. 

If you have any changes to merge, please do so and I will update the cocoapods accordingly.
